version: "3.4"
services:
  app:
    image: prime-item-tracker:latest
    restart: unless-stopped
    networks:
      - traefik_public
    labels:
      - "traefik.http.routers.primetracker.rule=Host(`primetracker.davlin.io`)"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.services.primetracker.loadbalancer.server.port=3000"
      - "traefik.http.routers.primetracker.entrypoints=https"
      - "traefik.http.routers.primetracker.tls=true"

networks:
  traefik_public:
    external: true
