version: "3.4"
services:
  app:
    image: mp1-item-tracker:latest
    restart: unless-stopped
    networks:
      - traefik_public
    labels:
      - "traefik.http.routers.prime1tracker.rule=Host(`prime1tracker.davlin.io`)"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.services.prime1tracker.loadbalancer.server.port=3000"
      - "traefik.http.routers.prime1tracker.entrypoints=https"
      - "traefik.http.routers.prime1tracker.tls=true"

networks:
  traefik_public:
    external: true
